### ISSUE TITLE
Cant run(

### ISSUE THREAD

**Issue by ArtemS2** [AD2011/phonebook.cz_scrapper#1]
[+] Running Phonebook.cz scrapper!

Traceback (most recent call last):
  File "/home/artem/builds/phonebook.cz_scrapper/phonebook.py", line 124, in <module>
    main()
  File "/home/artem/builds/phonebook.cz_scrapper/phonebook.py", line 108, in main
    process_domain(args.url, target, target_type, output_file)
  File "/home/artem/builds/phonebook.cz_scrapper/phonebook.py", line 71, in process_domain
    data = make_request(key)
           ^^^^^^^^^^^^^^^^^
  File "/home/artem/builds/phonebook.cz_scrapper/phonebook.py", line 38, in make_request
    key = json.loads(key)['id']
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AD2011** [comment]
Have you added the phonebook.cz key?

**Comment by ArtemS2** [comment]
yes, but maybe it’s a matter of recent changes, it seems they have limited access
