### ISSUE TITLE
Error termux 

### ISSUE THREAD

**Issue by bytccoin** [AD2011/phonebook.cz_scrapper#2]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/phonebook3/phonebook.py", line 124, in <module>
    main()
  File "/data/data/com.termux/files/home/phonebook3/phonebook.py", line 108, in main
    process_domain(args.url, target, target_type, output_file)
  File "/data/data/com.termux/files/home/phonebook3/phonebook.py", line 71, in process_domain
    data = make_request(key)
           ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/phonebook3/phonebook.py", line 38, in make_request
    key = json.loads(key)['id']
          ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AD2011** [comment]
Did you add API key in the phonebook.py file?
